spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리를 보기 좋게 포맷
        use_sql_comments: true  # SQL 주석 활성화
        jdbc:
          batch_size: 30  # 배치 처리 최적화 예시 (선택 사항)
logging:
  level:
    org.hibernate.SQL: DEBUG       # SQL 쿼리 로그 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 바인딩된 파라미터 출력